name: NewBedWars
version: '${project.version}'
main: n.plugins.newbedwars.NewBedWars
author: NewadminOFC
description: BedWars 1.8.8 com setup completo in-game e varios modos
depend: [Citizens]
commands:
  bw:
    description: Comando principal do BedWars
    usage: /bw
    aliases: [bedwars]
  lobby:
    description: Volta para o lobby principal
    usage: /lobby
permissions:
  newbedwars.admin:
    description: Permite administrar arenas BedWars
    default: op
  newbedwars.teamselect:
    description: Permite escolher a cor do time no lobby de espera
    default: op
