name: NewBedWars
version: '${project.version}'
main: n.plugins.newbedwars.NewBedWars
authors:
  - NewAdmin
  - Kuro
description: NewBW sistema com interface simples com menus para facilitar o setup do bw
depend: [Citizens]
commands:
  bw:
    description: Comando principal do BedWars
    usage: /bw
    aliases: [bedwars]
  g:
    description: Fala globalmente com todos da arena atual
    usage: /g <mensagem>
    aliases: [global]
  lobby:
    description: Volta para o lobby principal
    usage: /lobby
permissions:
  newbedwars.admin:
    description: Permite administrar arenas BedWars
    default: op
  newbedwars.teamselect:
    description: Permite escolher a cor do time no lobby de espera
    default: op
